version: '3'
services:
  solucx-web:
    image: solucx:latest
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/solucx
      - ./docker-assets/nginx/solucx.conf:/etc/nginx/sites-enabled/solucx.conf
      - ./docker-assets/php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./docker-assets/php-fpm/www.conf:/etc/php/7.4/fpm/pool.d/www.conf